In [6]:
import pandas as pd
import random

data = {
    'Tipe Ujian' : ['UTS1', 'UAS1', 'UTS2', 'UAS2']*3,
    'Mata Pelajaran' : ['Fisika']*4 + ['Matematika']*4+['Statistika']*4,
    'Rata2 Waktu Belajar (menit)' : [random.choice(range(200, 800)) for i in range(12)],
    'Rata2 Nilai Ujian' : [random.choice(range(40, 100)) for i in range(12)] 
}

df = pd.DataFrame(data)
df

   Tipe Ujian Mata Pelajaran  Rata2 Waktu Belajar (menit)  Rata2 Nilai Ujian
0        UTS1         Fisika                          260                 87
1        UAS1         Fisika                          637                 84
2        UTS2         Fisika                          454                 95
3        UAS2         Fisika                          316                 64
4        UTS1     Matematika                          500                 74
5        UAS1     Matematika                          484                 82
6        UTS2     Matematika                          291                 92
7        UAS2     Matematika                          306                 45
8        UTS1     Statistika                          789                 54
9        UAS1     Statistika                          497                 63
10       UTS2     Statistika                          534                 48
11       UAS2     Statistika                          742                 67



---



---

## Soal 1. Data Cleaning

Lakukan sorting data berdasarkan Rata2 nilai ujian dari terbesar ke terkecil

*   Lakukan sorting data berdasarkan Rata2 nilai ujian dari terbesar ke terkecil

In [8]:
#code here
df.sort_values('Rata2 Nilai Ujian', ascending=False)

   Tipe Ujian Mata Pelajaran  Rata2 Waktu Belajar (menit)  Rata2 Nilai Ujian
2        UTS2         Fisika                          454                 95
6        UTS2     Matematika                          291                 92
0        UTS1         Fisika                          260                 87
1        UAS1         Fisika                          637                 84
5        UAS1     Matematika                          484                 82
4        UTS1     Matematika                          500                 74
11       UAS2     Statistika                          742                 67
3        UAS2         Fisika                          316                 64
9        UAS1     Statistika                          497                 63
8        UTS1     Statistika                          789                 54
10       UTS2     Statistika                          534                 48
7        UAS2     Matematika                          306                 45

Expected output:

(Output bisa berbeda-beda)

![alt text](https://drive.google.com/uc?id=1iv8P-LDdN3WpTVX9qST3kL7QSNSDiOc2)



---



---

<h2>Soal 2: Data Restructuring</h2>

Jelaskan itu pivoting dan melting data


Pivoting adalah suatu pengubahan bentuk data dengan memutar data yang terletak di baris menjadi di column. coba perhatikan gambar di atas.

---

Melting adalah ‘unpivoting’, melting mengubah suatu data dengan memutar dari yang tadinya berada di posisi column menjadi di posisi row.

---

<h2>Soal 3: Reshaping Data 1</h2>

In [ ]:
import pandas as pd
import random

data = {
    'Tipe Ujian' : ['UTS1', 'UAS1', 'UTS2', 'UAS2']*3,
    'Mata Pelajaran' : ['Fisika']*4 + ['Matematika']*4+['Statistika']*4,
    'Rata2 Waktu Belajar (menit)' : [random.choice(range(200, 800)) for i in range(12)],
    'Rata2 Nilai Ujian' : [random.choice(range(40, 100)) for i in range(12)] 
}

df = pd.DataFrame(data)
df

   Tipe Ujian Mata Pelajaran  Rata2 Waktu Belajar (menit)  Rata2 Nilai Ujian
0        UTS1         Fisika                          403                 74
1        UAS1         Fisika                          618                 90
2        UTS2         Fisika                          757                 46
3        UAS2         Fisika                          213                 84
4        UTS1     Matematika                          699                 94
5        UAS1     Matematika                          350                 67
6        UTS2     Matematika                          755                 73
7        UAS2     Matematika                          572                 48
8        UTS1     Statistika                          567                 41
9        UAS1     Statistika                          508                 99
10       UTS2     Statistika                          242                 68
11       UAS2     Statistika                          443                 88

Perhatikan data di atas, kemudian ubahlah bentuknya agar sesuai yang di harapkan.

In [31]:
#code here
pivot_table_df= pd.pivot_table(
    df, index='Tipe Ujian',
    columns='Mata Pelajaran',
    values=['Rata2 Nilai Ujian','Rata2 Waktu Belajar (menit)'],
    aggfunc='sum')
print(pivot_table_df)

               Rata2 Nilai Ujian                        \
Mata Pelajaran            Fisika Matematika Statistika
Tipe Ujian
UAS1                          84         82         63
UAS2                          64         45         67
UTS1                          87         74         54
UTS2                          95         92         48

               Rata2 Waktu Belajar (menit)
Mata Pelajaran                      Fisika Matematika Statistika
Tipe Ujian
UAS1                                   637        484        497
UAS2                                   316        306        742
UTS1                                   260        500        789
UTS2                                   454        291        534

Expected Result:

(Output bisa berbeda-beda)

![alt text](https://drive.google.com/uc?id=1XufsfqZe7-XZLsb92SpATexy-QRZE0ow)



---



---

<h2>Soal 4: Reshaping Data 2</h2>

In [32]:
import pandas as pd

data = {
    'Hari' : ['Sabtu', 'Minggu'],
    'Kebun Binatang' : [271, 399],
    'Dufan' : [501, 700],
    'Disney' : [1000, 1001],
    'Bali' : [900, 803]
}
df = pd.DataFrame(data).set_index('Hari')
df

        Kebun Binatang  Dufan  Disney  Bali
Hari
Sabtu              271    501    1000   900
Minggu             399    700    1001   803

diatas adalah data tentang jumlah pengunjung di berbagai tempat hiburan, ubahlah struktur data tersebut sehingga sesuai dengan hasil yang diharapkan.

In [38]:
#code here
df_long = df.reset_index().melt(
    id_vars='Hari',
    var_name='Tempat Hiburan',
    value_name='Jumlah Pengunjung'
)

print(df_long)

     Hari  Tempat Hiburan  Jumlah Pengunjung
0   Sabtu  Kebun Binatang                271
1  Minggu  Kebun Binatang                399
2   Sabtu           Dufan                501
3  Minggu           Dufan                700
4   Sabtu          Disney               1000
5  Minggu          Disney               1001
6   Sabtu            Bali                900
7  Minggu            Bali                803

Expected Result:

(Output bisa berbeda-beda)

![alt text](https://drive.google.com/uc?id=159mIqcyfeD30EEcyZmmkovORa6cZDLtn)



---



---

<h2>Soal 5: Data Enrichment</h2>

Lakukan binning data menggunakan qcut sehingga sesuai hasil yang diharapkan

In [52]:
#code here
import pandas as pd
import random

data = {
    'Tipe Ujian' : ['UTS1', 'UAS1', 'UTS2', 'UAS2']*3,
    'Mata Pelajaran' : ['Fisika']*4 + ['Matematika']*4+['Statistika']*4,
    'Rata2 Waktu Belajar (menit)' : [random.choice(range(200, 800)) for i in range(12)],
    'Rata2 Nilai Ujian' : [random.choice(range(40, 100)) for i in range(12)] 
}

df = pd.DataFrame(data)
df

# pd.qcut(df['Rata2 Nilai Ujian'],q=3)
labels=['tidak lulus','remedial','lulus']
df['kelulusan']=pd.qcut(df['Rata2 Nilai Ujian'],q=3, labels=labels)
df

,Tipe Ujian,Mata Pelajaran,Rata2 Waktu Belajar (menit),Rata2 Nilai Ujian,kelulusan
0,UTS1,Fisika,239,84,lulus
1,UAS1,Fisika,450,55,tidak lulus
2,UTS2,Fisika,608,82,lulus
3,UAS2,Fisika,497,68,remedial
4,UTS1,Matematika,229,81,remedial
5,UAS1,Matematika,249,79,remedial
6,UTS2,Matematika,697,72,remedial
7,UAS2,Matematika,331,97,lulus
8,UTS1,Statistika,778,51,tidak lulus
9,UAS1,Statistika,213,58,tidak lulus
10,UTS2,Statistika,338,91,lulus
11,UAS2,Statistika,419,55,tidak lulus

Expected Output:

(Output bisa berbeda-beda)

![alt text](https://drive.google.com/uc?id=1h2_u5_xhD1_QtPpItTj-o3lljHhnr4XS)



---



---